--- 
abstract: Auto-create URI objects from columns
author: Nathan Gray <kolibrie@cpan.org>
build_requires: 
  Class::Accessor::Grouped: 0
  DBD::SQLite: 1.11
  File::Spec::Functions: 0
  Test::Builder::Module: 0
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-InflateColumn-URI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Grouped: 0.03
  DBIx::Class: 0.07005
  URI: 0
  perl: 5.6.1
version: 0.01002
